var results = [
  { rank: 1, name: 'Andy Benko', recent: false, category: 'M', team: 'Paddy Power', boat_number: 'I', result: '9:28.8', pace: '1:28.9', power: '498.6' },
  { rank: 2, name: 'Dave Marshall', recent: false, category: 'M', team: 'MAD', boat_number: 'I', result: '9:35.2', pace: '1:29.9', power: '482.1' },
  { rank: 3, name: 'PP Lee Bawn', recent: false, category: 'M', team: 'Paddy Power', boat_number: 'I', result: '9:40.4', pace: '1:30.7', power: '469.3' },
  { rank: 4, name: 'Brett Steels', recent: false, category: 'M', team: 'Sub 7', boat_number: 'I', result: '9:45.3', pace: '1:31.5', power: '457.6' },
  { rank: 5, name: '1 Ross Love', recent: false, category: 'M', team: 'Paddy Power', boat_number: 'I', result: '9:52.7', pace: '1:32.6', power: '440.7' },
  { rank: 6, name: 'Dave Chmilowskyj', recent: false, category: 'M', team: 'Team Oarsome', boat_number: 'I', result: '10:10.2', pace: '1:35.3', power: '403.8' },
  { rank: 7, name: 'Bjorn_Stensheim', recent: true, category: 'M', team: 'RowPro Rowers', boat_number: 'I', result: '10:12.6', pace: '1:35.7', power: '399.1' },
  { rank: 8, name: 'DavidHolmberg', recent: false, category: 'm', team: 'Free Spirits', boat_number: 'I', result: '10:13.0', pace: '1:35.8', power: '398.3' },
  { rank: 9, name: 'Liefcat', recent: false, category: 'M', team: 'Free Spirits', boat_number: 'I', result: '10:14.7', pace: '1:36.0', power: '395.0' },
  { rank: 10, name: 'Alastair Peake', recent: false, category: 'm', team: 'Sub 7', boat_number: 'I', result: '10:15.6', pace: '1:36.2', power: '393.3' },
  { rank: 11, name: 'EricL', recent: false, category: 'M', team: 'FIRT', boat_number: 'I', result: '10:16.0', pace: '1:36.3', power: '392.5' },
  { rank: 12, name: 'Pete Marston', recent: false, category: 'M', team: 'MAD', boat_number: 'I', result: '10:17.5', pace: '1:36.5', power: '389.7' },
  { rank: 13, name: 'David Byrnes', recent: false, category: 'm', team: 'Sub 7', boat_number: 'I', result: '10:20.3', pace: '1:36.9', power: '384.4' },
  { rank: 14, name: 'Arwed Egger', recent: false, category: 'm', team: 'RowPro Rowers', boat_number: 'I', result: '10:20.7', pace: '1:37.0', power: '383.7' },
  { rank: 15, name: 'R2C2', recent: false, category: 'M', team: 'FIRT', boat_number: 'I', result: '10:21.5', pace: '1:37.1', power: '382.2' },
  { rank: 16, name: 'Howard Brammer', recent: false, category: 'M', team: 'Fitness Matters', boat_number: 'I', result: '10:22.3', pace: '1:37.2', power: '380.7' },
  { rank: 17, name: 'Amadee Pelgrim', recent: false, category: 'M', team: 'RowPro Rowers', boat_number: 'I', result: '10:23.1', pace: '1:37.4', power: '379.3' },
  { rank: 18, name: 'Jens Kristian Dam', recent: false, category: 'm', team: 'Sub 7', boat_number: 'I', result: '10:23.8', pace: '1:37.5', power: '378.0' },
  { rank: 19, name: 'Glynn Powell', recent: false, category: 'M', team: 'Sub 7', boat_number: 'II', result: '10:24.8', pace: '1:37.6', power: '376.2' },
  { rank: 20, name: 'Steve Sidaway', recent: false, category: 'M', team: 'Sub 7', boat_number: 'II', result: '10:25.2', pace: '1:37.7', power: '375.4' },
  { rank: 21, name: 'Brenan', recent: false, category: 'M', team: 'Tribesports', boat_number: 'I', result: '10:25.3', pace: '1:37.7', power: '375.3' },
  { rank: 22, name: 'Andy J Pearce', recent: false, category: 'M', team: 'C2TweetCrew', boat_number: 'I', result: '10:28.8', pace: '1:38.2', power: '369.0' },
  { rank: 23, name: 'Jason McCormack', recent: false, category: 'M', team: 'Paddy Power', boat_number: 'II', result: '10:30.5', pace: '1:38.5', power: '366.1' },
  { rank: 24, name: 'Warren Matthews', recent: false, category: 'M', team: 'Sub 7', boat_number: 'II', result: '10:32.3', pace: '1:38.8', power: '362.9' },
  { rank: 25, name: 'Robert Jones', recent: false, category: 'M', team: 'Sub 7', boat_number: 'III', result: '10:33.1', pace: '1:38.9', power: '361.6' },
  { rank: 26, name: 'hugault', recent: false, category: 'M', team: 'FIRT', boat_number: 'I', result: '10:33.2', pace: '1:38.9', power: '361.4' },
  { rank: 27, name: 'Hillclimber', recent: true, category: 'M', team: 'Forum Flyers', boat_number: 'I', result: '10:33.8', pace: '1:39.0', power: '360.4' },
  { rank: 28, name: 'Vivien Marmelat', recent: true, category: 'M', team: 'FIRT', boat_number: 'II', result: '10:35.3', pace: '1:39.3', power: '357.8' },
  { rank: 29, name: 'Casey Clarke', recent: false, category: 'M', team: 'Sub 7', boat_number: 'III', result: '10:36.2', pace: '1:39.4', power: '356.3' },
  { rank: 30, name: 'Jean-Charles RS', recent: true, category: 'M', team: 'FIRT', boat_number: 'II', result: '10:39.2', pace: '1:39.9', power: '351.3' },
  { rank: 31, name: 'Ben M', recent: false, category: 'M', team: 'Tribesports', boat_number: 'I', result: '10:39.9', pace: '1:40.0', power: '350.2' },
  { rank: 32, name: 'Joshua Cherwinski', recent: false, category: 'm', team: 'Paddy Power', boat_number: 'I', result: '10:40.2', pace: '1:40.0', power: '349.7' },
  { rank: 33, name: 'Frank Noorlander', recent: false, category: 'M', team: 'Forum Flyers', boat_number: 'I', result: '10:42.0', pace: '1:40.3', power: '346.7' },
  { rank: 34, name: 'jason2tall', recent: false, category: 'M', team: 'Free Spirits', boat_number: 'I', result: '10:42.8', pace: '1:40.4', power: '345.4' },
  { rank: 35, name: 'haaico', recent: false, category: 'M', team: 'Free Spirits', boat_number: 'I', result: '10:45.0', pace: '1:40.8', power: '341.9' },
  { rank: 36, name: 'Larry Tait', recent: false, category: 'M', team: 'Team Oarsome', boat_number: 'I', result: '10:47.7', pace: '1:41.2', power: '337.7' },
  { rank: 37, name: 'Lars Kofod', recent: false, category: 'M', team: 'Sub 7', boat_number: 'III', result: '10:48.3', pace: '1:41.3', power: '336.7' },
  { rank: 38, name: 'Paosullivan', recent: true, category: 'M', team: 'Paddy Power', boat_number: 'II', result: '10:49.3', pace: '1:41.5', power: '335.2' },
  { rank: 39, name: 'AARobert diffley', recent: false, category: 'm', team: 'Paddy Power', boat_number: 'II', result: '10:50.0', pace: '1:41.6', power: '334.1' },
  { rank: 40, name: 'Paul Victory', recent: false, category: 'M', team: 'Free Spirits', boat_number: 'II', result: '10:52.3', pace: '1:41.9', power: '330.6' },
  { rank: 41, name: 'JEFF JANEAU', recent: true, category: 'M', team: 'FIRT', boat_number: 'II', result: '10:53.7', pace: '1:42.1', power: '328.5' },
  { rank: 42, name: 'Colin O\'Neill', recent: false, category: 'm', team: 'Paddy Power', boat_number: 'II', result: '10:55.5', pace: '1:42.4', power: '325.8' },
  { rank: 43, name: 'Alfred Okello', recent: false, category: 'm', team: 'Sub 7', boat_number: 'II', result: '10:56.1', pace: '1:42.5', power: '324.9' },
  { rank: 44, name: 'Andy Osborn', recent: false, category: 'M', team: 'Sub 7', boat_number: 'IV', result: '10:56.6', pace: '1:42.6', power: '324.1' },
  { rank: 45, name: 'Jon Bone', recent: false, category: 'M', team: 'Team Oarsome', boat_number: 'I', result: '10:56.6', pace: '1:42.6', power: '324.1' },
  { rank: 46, name: 'attieh crossfit', recent: false, category: 'M', team: 'FIRT', boat_number: 'III', result: '10:57.2', pace: '1:42.7', power: '323.2' },
  { rank: 47, name: 'Mercier', recent: false, category: 'm', team: 'FIRT', boat_number: 'I', result: '10:58.9', pace: '1:43.0', power: '320.7' },
  { rank: 48, name: 'bojam', recent: true, category: 'm', team: 'Sub 7', boat_number: 'III', result: '11:02.2', pace: '1:43.5', power: '316.0' },
  { rank: 49, name: 'Andr Budzien', recent: false, category: 'M', team: 'SYC Rowing Crew', boat_number: 'I', result: '11:02.6', pace: '1:43.5', power: '315.4' },
  { rank: 50, name: 'Rowland Hills', recent: false, category: 'M', team: 'Sub 7', boat_number: 'IV', result: '11:04.2', pace: '1:43.8', power: '313.1' },
  { rank: 51, name: '2444 Rob Smiff', recent: true, category: 'M', team: 'Penobscot River IRC', boat_number: 'I', result: '11:05.0', pace: '1:43.9', power: '312.0' },
  { rank: 52, name: 'AAPaul Buchanan', recent: false, category: 'M', team: 'Paddy Power', boat_number: 'III', result: '11:05.5', pace: '1:44.0', power: '311.3' },
  { rank: 53, name: 'Euan Stronach', recent: false, category: 'M', team: 'Sub 7', boat_number: 'IV', result: '11:05.9', pace: '1:44.0', power: '310.7' },
  { rank: 54, name: 'Looping', recent: false, category: 'm', team: 'FIRT', boat_number: 'II', result: '11:09.0', pace: '1:44.5', power: '306.4' },
  { rank: 55, name: 'Bill_Schmidt', recent: false, category: 'm', team: 'Empty the Tanks', boat_number: 'I', result: '11:10.5', pace: '1:44.8', power: '304.4' },
  { rank: 56, name: 'Dave Barber', recent: false, category: 'M', team: 'Sub 7', boat_number: 'V', result: '11:13.7', pace: '1:45.3', power: '300.1' },
  { rank: 57, name: 'Rod Chinn', recent: false, category: 'M', team: 'Sub 7', boat_number: 'V', result: '11:13.9', pace: '1:45.3', power: '299.8' },
  { rank: 58, name: 'Felton Humble', recent: false, category: 'M', team: 'Free Spirits', boat_number: 'II', result: '11:15.8', pace: '1:45.6', power: '297.3' },
  { rank: 59, name: 'Chris Whale', recent: false, category: 'M', team: 'Forum Flyers', boat_number: 'I', result: '11:16.7', pace: '1:45.7', power: '296.1' },
  { rank: 60, name: 'Roger Bjarm Fornebo', recent: false, category: 'M', team: 'Sub 7', boat_number: 'V', result: '11:18.1', pace: '1:46.0', power: '294.3' },
  { rank: 61, name: 'Will Haskell', recent: false, category: 'm', team: 'Forum Flyers', boat_number: 'I', result: '11:19.6', pace: '1:46.2', power: '292.3' },
  { rank: 62, name: 'andy warner', recent: true, category: 'M', team: 'Sub 7', boat_number: 'VI', result: '11:20.8', pace: '1:46.4', power: '290.8' },
  { rank: 63, name: 'David SAGON', recent: false, category: 'm', team: 'FIRT', boat_number: 'III', result: '11:21.5', pace: '1:46.5', power: '289.9' },
  { rank: 64, name: 'Oranj', recent: false, category: 'm', team: 'Independent', boat_number: 'I', result: '11:23.0', pace: '1:46.7', power: '288.0' },
  { rank: 65, name: 'Mark Underwood', recent: false, category: 'm', team: 'Paddy Power', boat_number: 'III', result: '11:23.4', pace: '1:46.8', power: '287.5' },
  { rank: 66, name: 'D Wiklander', recent: false, category: 'M', team: 'Rote 87 RK', boat_number: 'I', result: '11:25.1', pace: '1:47.0', power: '285.3' },
  { rank: 67, name: 'aurelienusv', recent: false, category: 'M', team: 'FIRT', boat_number: 'III', result: '11:27.4', pace: '1:47.4', power: '282.5' },
  { rank: 68, name: 'Eric Perlorca', recent: false, category: 'M', team: 'Paddy Power', boat_number: 'III', result: '11:28.5', pace: '1:47.6', power: '281.1' },
  { rank: 69, name: 'Xav salamandre', recent: false, category: 'M', team: 'FIRT', boat_number: 'III', result: '11:33.9', pace: '1:48.4', power: '274.6' },
  { rank: 70, name: 'Troy M', recent: false, category: 'M', team: 'Paddy Power', boat_number: 'III', result: '11:35.6', pace: '1:48.7', power: '272.6' },
  { rank: 71, name: 'Jon P Taylor', recent: false, category: 'm', team: 'Free Spirits', boat_number: 'II', result: '11:36.7', pace: '1:48.9', power: '271.3' },
  { rank: 72, name: 'David Plumb', recent: false, category: 'm', team: 'Free Spirits', boat_number: 'II', result: '11:37.0', pace: '1:48.9', power: '271.0' },
  { rank: 73, name: 'patrice CORNUT', recent: false, category: 'M', team: 'FIRT', boat_number: 'IV', result: '11:38.6', pace: '1:49.2', power: '269.1' },
  { rank: 74, name: 'Joe    A  Keating', recent: false, category: 'm', team: 'Paddy Power', boat_number: 'IV', result: '11:41.4', pace: '1:49.6', power: '265.9' },
  { rank: 75, name: 'Funkyrower', recent: false, category: 'M', team: 'The Banana Boat', boat_number: 'I', result: '11:42.7', pace: '1:49.8', power: '264.4' },
  { rank: 76, name: 'Stuart Thorp', recent: false, category: 'M', team: 'C2TweetCrew', boat_number: 'I', result: '11:44.4', pace: '1:50.1', power: '262.5' },
  { rank: 77, name: 'Ruud Jackel', recent: true, category: 'M', team: 'RowPro Rowers', boat_number: 'I', result: '11:56.5', pace: '1:52.0', power: '249.4' },
  { rank: 78, name: 'Jason Robert Harris', recent: false, category: 'M', team: 'Sub 7', boat_number: 'VI', result: '11:59.2', pace: '1:52.4', power: '246.6' },
  { rank: 79, name: 'Remy Coubel', recent: false, category: 'M', team: 'FIRT', boat_number: 'IV', result: '12:00.0', pace: '1:52.5', power: '245.8' },
  { rank: 80, name: 'Yvonne Apitz', recent: false, category: 'F', team: 'Sub 7', boat_number: 'I', result: '12:03.0', pace: '1:53.0', power: '242.8' },
  { rank: 81, name: 'hjs', recent: false, category: 'M', team: 'Forum Flyers', boat_number: 'II', result: '12:03.0', pace: '1:53.0', power: '242.8' },
  { rank: 82, name: 'Borut Hafner', recent: false, category: 'm', team: 'C2TweetCrew', boat_number: 'I', result: '12:05.6', pace: '1:53.4', power: '240.2' },
  { rank: 83, name: 'Carol Woodward', recent: false, category: 'f', team: 'Sub 7', boat_number: 'II', result: '12:09.6', pace: '1:54.0', power: '236.2' },
  { rank: 84, name: 'Volkert Wagenar', recent: false, category: 'M', team: 'Sub 7', boat_number: 'VI', result: '12:12.3', pace: '1:54.4', power: '233.6' },
  { rank: 85, name: 'Carlos Rodriguez', recent: false, category: 'm', team: 'Sub 7', boat_number: 'IV', result: '12:15.2', pace: '1:54.9', power: '230.9' },
  { rank: 86, name: 'Rob Drury', recent: false, category: 'm', team: 'Empty the Tanks', boat_number: 'I', result: '12:15.4', pace: '1:54.9', power: '230.7' },
  { rank: 87, name: 'Mike Brownjohn', recent: false, category: 'm', team: 'DLC Gidea Park', boat_number: 'I', result: '12:15.5', pace: '1:54.9', power: '230.6' },
  { rank: 88, name: 'Rob C', recent: false, category: 'M', team: 'Free Spirits', boat_number: 'III', result: '12:16.7', pace: '1:55.1', power: '229.5' },
  { rank: 89, name: 'Julie Steventon', recent: false, category: 'F', team: 'Free Spirits', boat_number: 'I', result: '12:19.9', pace: '1:55.6', power: '226.5' },
  { rank: 90, name: 'Simone Chaumiole', recent: false, category: 'F', team: 'FIRT', boat_number: 'I', result: '12:20.8', pace: '1:55.7', power: '225.7' },
  { rank: 91, name: 'Dennis Lindenbaum', recent: true, category: 'm', team: 'Free Spirits', boat_number: 'III', result: '12:28.0', pace: '1:56.9', power: '219.2' },
  { rank: 92, name: 'Tinaosullivan', recent: true, category: 'f', team: 'Paddy Power', boat_number: 'I', result: '12:29.7', pace: '1:57.1', power: '217.7' },
  { rank: 93, name: 'Godfrey Tarling', recent: false, category: 'M', team: 'Sub 7', boat_number: 'VII', result: '12:35.7', pace: '1:58.1', power: '212.6' },
  { rank: 94, name: 'Debbie Barber', recent: false, category: 'F', team: 'Forum Flyers', boat_number: 'I', result: '12:36.8', pace: '1:58.2', power: '211.7' },
  { rank: 95, name: 'thomas jean philippe', recent: true, category: 'm', team: 'FIRT', boat_number: 'IV', result: '12:39.3', pace: '1:58.6', power: '209.6' },
  { rank: 96, name: 'Andy Tripp', recent: false, category: 'M', team: 'Tribesports', boat_number: 'I', result: '12:39.4', pace: '1:58.7', power: '209.5' },
  { rank: 97, name: 'Sarah Doyle PP', recent: true, category: 'F', team: 'Paddy Power', boat_number: 'II', result: '12:49.1', pace: '2:00.2', power: '201.7' },
  { rank: 98, name: 'Anita Pearce', recent: false, category: 'F', team: 'C2TweetCrew', boat_number: 'I', result: '12:50.1', pace: '2:00.3', power: '200.9' },
  { rank: 99, name: 'Mark Kaehler', recent: false, category: 'M', team: 'Empty the Tanks', boat_number: 'I', result: '12:51.9', pace: '2:00.6', power: '199.5' },
  { rank: 100, name: 'Lucy OB', recent: false, category: 'f', team: 'Paddy Power', boat_number: 'III', result: '12:52.9', pace: '2:00.8', power: '198.7' },
  { rank: 101, name: 'Abby Diaz', recent: false, category: 'F', team: 'Paddy Power', boat_number: 'IV', result: '12:56.0', pace: '2:01.3', power: '196.3' },
  { rank: 102, name: 'Rick Bayko', recent: false, category: 'm', team: 'Forum Flyers', boat_number: 'II', result: '13:03.0', pace: '2:02.3', power: '191.1' },
  { rank: 103, name: 'Annette Wammen', recent: true, category: 'f', team: 'RowPro Rowers', boat_number: 'I', result: '13:05.8', pace: '2:02.8', power: '189.1' },
  { rank: 104, name: 'Georgina Price', recent: false, category: 'F', team: 'Forum Flyers', boat_number: 'II', result: '13:15.2', pace: '2:04.3', power: '182.5' },
  { rank: 105, name: 'Dougie Lawson', recent: false, category: 'M', team: 'Sub 7', boat_number: 'VII', result: '13:17.4', pace: '2:04.6', power: '181.0' },
  { rank: 106, name: 'Karla R', recent: true, category: 'F', team: 'Tribesports', boat_number: 'I', result: '13:18.4', pace: '2:04.7', power: '180.3' },
  { rank: 107, name: 'Jack Gilmore', recent: false, category: 'M', team: 'Forum Flyers', boat_number: 'II', result: '13:41.7', pace: '2:08.4', power: '165.4' },
  { rank: 108, name: 'Roger Burrell', recent: true, category: 'm', team: 'Free Spirits', boat_number: 'III', result: '13:55.1', pace: '2:10.5', power: '157.5' },
  { rank: 109, name: 'PeggyH', recent: false, category: 'f', team: 'Free Spirits', boat_number: 'II', result: '14:05.0', pace: '2:12.0', power: '152.1' },
  { rank: 110, name: 'Mikael Calonius', recent: true, category: 'M', team: 'Forum Flyers', boat_number: 'II', result: '15:00.0', pace: '2:20.6', power: '125.9' },
  { rank: 111, name: 'DJ Benny', recent: false, category: 'm', team: 'SYC Rowing Crew', boat_number: 'I', result: '15:02.5', pace: '2:21.0', power: '124.8' },
  { rank: 112, name: 'Emmie Baker', recent: false, category: 'f', team: 'Forum Flyers', boat_number: 'III', result: '24:46.5', pace: '3:52.3', power: '27.9' },
  { rank: 113, name: 'Adam Mell', recent: false, category: 'M', team: 'C2TweetCrew', boat_number: 'I', result: '30:00.0', pace: '4:41.3', power: '15.7' }
];
var teamColors = {
  'Paddy Power': '2bdf2b',
  'MAD': 'aaaaaa',
  'Sub 7': '7777ff',
  'Team Oarsome': 'f96606',
  'RowPro Rowers': '47c8c8',
  'Free Spirits': 'c0c0ff',
  'FIRT': 'f4a01d',
  'Fitness Matters': '383ec8',
  'Tribesports': 'f0ab00',
  'C2TweetCrew': 'fdfd00',
  'Forum Flyers': 'ab44d0',
  'SYC Rowing Crew': 'eeeeee',
  'Penobscot River IRC': 'ccd9c2',
  'Empty the Tanks': 'ec321a',
  'Independent': 'f253f2',
  'Rote 87 RK': 'bef781',
  'The Banana Boat': 'cccc00',
  'DLC Gidea Park': '79bb93'
};
